### ISSUE TITLE
Angabe der Größe für die zip-Datei

### ISSUE THREAD

**Issue by p-Enzi** [kaystrobach/TYPO3.folder#3]
Die Einzelgrößen der Dateien sind ja bereits ermittelt.
Damit sich die Leute nicht wundern, warum der Download
einiger Bilder sooo lange dauert.

**Comment by kaystrobach** [comment]
mhmm, um die echte größe der zip datei anzugeben, müsste jeweils das archiv erzeugt werden (je view), damit wird nach meiner meinung viel rechenleistung verschwendet, deswegen finde ich das schwierig.

Während des Downloads die Größe anzugeben, sollte dagegen kein Problem sein, da in dem Moment ja die Größe der Datei bekannt ist. Hier könnt dann der Browser eine entsprechende Anzeige machen.

**Comment by p-Enzi** [comment]
Da im Block oben drüber ja die Größe der einzelnen Dateien
glaube ich nicht, dass es viel Rechenleistung braucht diese paar Zahlen zu addieren.
Ib die Zip dann viel kleiner wird, darf bei JPGs ohnehin bezweifelt werden.
Für den Nutzer ist es wichtig zu sehen ob es eher 10MB oder eher 500MB
sind. Dann kann er sich überlegen ob er es gleich macht oder doch erst zuhause
per WLAN.

**Comment by kaystrobach** [comment]
mhmm, ok, hier treffen sich wieder die Anwendungsfälle :D. In meinen Szenarien sind es meistens Textdateien und da macht es einen erheblichen Unterschied.

Außerdem werden ja auch die Unterordne gepackt (das Addieren ist aber auch dort kein Problem).

Ich denke nochmal drüber nach, wenn will ich schon die richtige Größe angeben ...

**Comment by p-Enzi** [comment]
Bei Textdateien ist die Größe doch eher klein?
Und das Packverhältnis dürfte statistisch fast immer gleich sein.

Ansonsten:
Es ist doch wichtig, ob es
kByte, MByte oder GByte sind.

Im Zweifel tuts doch auch eine ~ Tilde
vor der Grössenangabe.

Wenns dann beim Zippen weniger Bytes als angegeben werden,
dann gehts halt schneller im Download, ist doch prima.

Die Obergrenze als Summe aller Dateigrössen
wird in keinem Fall überschritten - oder ;-)

**Comment by kaystrobach** [comment]
wie beschrieben, raten finde ich etwas schwierig, maximal angaben auch :(
