### ISSUE TITLE
TYPO3 6.2

### ISSUE THREAD

**Issue by breml** [kaystrobach/TYPO3.folder#8]
Hi

Are there any plans to make TYPO3.folder compatible with TYPO3 6.2?

Regards,
breml

**Comment by kaystrobach** [comment]
hi, where is it failing? it basicly should be compatible ... but i never tested, the customer installation is planned to be updated this year, so yes i will check later this year.

**Comment by breml** [comment]
First of all, the extension manager is complaining, because the required version of TYPO3 is higher than allowed by the plugin.
After forcefully installing the plugin, the following problem arises: 
In the TYPO3 backend there are no labels/desciptions shown for the fields when adding the plugin to a page. So I'm unable to configure the plugin.

**Comment by breml** [comment]
Ignored
